#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=00:30:00
#PBS -N app-convert-freesurfer-parcellation

parc=`jq -r '.parcellation' config.json`

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.3.2 ./convert.sh

echo "{\"datatype_tags\": [\"${parc}\"]}" > product.json

[ -f parcellation/parc.nii.gz ] && echo "complete" && cp label.json ./parcellation/ && exit 0 || echo "something went wrong. check logs" && exit 1

